services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: xui_bot
      MYSQL_USER: xui_user
      MYSQL_PASSWORD: 54asd54sa23
      MYSQL_ROOT_PASSWORD: root_password
  app:
    image: mhsenpc/xui_bot:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: xui_bot
      DATABASE_USERNAME: xui_user
      DATABASE_PASSWORD: 54asd54sa23
    depends_on:
      - mysql