package com.mhsenpc.v2raybot.bot.enums;

public enum UserStep {
    BUY_SELECT_PLAN,
    BUY_PAYMENT_METHOD,
    BUY_WAIT_FOR_RECEIPT,
    ADMIN_VIEW_ORDERS,
    ADMIN_WAITING_FOR_ORDER_COMMANDS,
    ADMIN_SELECT_PLAN,
    ADMIN_VIEW_USERS,
    ADMIN_VIEW_PLANS,
    ADMIN_WAITING_FOR_PLAN_COMMANDS
}
