name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      #SPRING_DATASOURCE_USERNAME: testuser
      #SPRING_DATASOURCE_PASSWORD: testpassword
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: testdb
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run tests with Maven
        run: mvn test
