name: Push Docker Image to Docker Hub

on:
  workflow_run:
    workflows: ["Build and Test Java Application"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v3

      - name: List target directory
        run: ls -al target

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create sample config.json
        run: cp src/main/resources/config.json.example storage/config.json

      - name: Get the current timestamp
        id: get-timestamp
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          echo "building docker image"
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/xui_bot:${{ env.VERSION }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/xui_bot:latest --push .

      - name: Done
        run: echo "Docker Image Push Done"
